services:
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  backend:
    build:
      context: .
    container_name: backend
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:

networks:
  appnetwork:
    driver: bridge
