services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  
  backend:
    build:
      context: .
    container_name: backend
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"
